### PR TITLE
Allows JSON fed charts to update data

### PR DESCRIPTION
**Pull request by robguilfoyle**
Currently this plugin only allows for array data charts to be bound and update. This PR allows for JSON based charts to also be bound and dynamically update. It does so through a change to the `_retrieveCurrentIds` allowing it to pull JSON keys, column keys, and row keys.

### CODE REVIEW

**Comment by green-arrow** [comment]
Closes #3

**Comment by green-arrow** [comment]
@robguilfoyle I just pushed v0.0.6 which has your fix for allowing JSON data. Feel free to give it a shot and let me know if you have any problems.

**Comment by robguilfoyle** [comment]
Thanks brutha, I actually ended up needing to create my own npm package from your repo, which I have been using in prod. If you update npm with version i’d be glad to switch back and help you maintain the repo.

**Comment by green-arrow** [comment]
No problem, appreciate the PR :smile: 

Version 0.0.6 should be published and available in NPM. I'd be happy to have the help in maintaining this repo.

**Pull request merged**
