### PR TITLE
same mixins to configure charts

### PR DESCRIPTION
**Pull request by thiagoc7**
Hi!

I'm using this gem in my project, and started trying to implement an architecture to use c3 api.
This is very basic, and I just implemented what I need in my project.

For now I just want to ask what you think, so then we can fill it with all c3 properties.

Latter we can start looking for changes with observers, and change the chart with c3 api methods, instead of destroy and recreate the chart.

Cheers!

### CODE REVIEW

**Comment by catmeme** [comment]
This looks great. It's a shame this hasn't been reviewed and merged yet.

**Comment by green-arrow** [comment]
@thiagoc7 and @catmeme  - sorry this has taken such a long time. I moved jobs and was not actually using this component for quite a long time.

It doesn't seem that this PR actually modifies any existing functionality, so no breaking changes would be introduced by merging this. I'm assuming this is meant to be completely additive and backwards compatible, is that correct? (I will make sure to pull down and test locally with some of my projects, I just want to be sure that was your goal :smile: )

Thank you for your work on this!

**Comment by green-arrow** [comment]
For some context, I originally made this because the existing integration ([ember-c3](https://github.com/Glavin001/ember-c3)) did not have ember-cli support. It looks like that has since changed and that addon does have ember-cli support, and is also actively maintained.

In looking at that library, I am wondering if it makes sense to have two separate libraries trying to accomplish the same thing. Maybe @Glavin001 could weigh in on this as well.

**Comment by Glavin001** [comment]
I am using Ember for work and hope to continue to use D3/C3 for work and other related projects, so Ember-C3 should be much healthier from here on. 
Unfortunately, I was not an early adopter of Ember-CLI at the time that many Ember-C3 users were requesting support -- since my projects at the time were locked into pre-Ember-CLI days and also not using Ember-C3 as much.

Now that I am all up-to-date with Ember (upgraded to Ember.js v2.2.0 today for work) I am confident that Ember-C3 will be well taken care of. Hope that helps! :smiley:

**Comment by catmeme** [comment]
Oh wow, @green-arrow I had just assumed your project to be the successor of ember-c3. It does look pretty mature at this point though.

@Glavin001 just saw you comment as I was writing a response. Seems like ember-c3 is going to be a great fit for our project. Thank you (both) for your hard work.

**Comment by green-arrow** [comment]
@Glavin001 thanks for the quick reply!

I am going to deprecate this package in favor of using `ember-c3`.

@thiagoc7 - I do appreciate your work on this PR and apologize for not getting to this sooner.

**Pull request closed without merging**
